import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import { SiteLocale } from 'constants/i18n.constants';
import { i18nConfig } from 'config/i18n.config';
import { dir } from 'i18next';
import Header from '@/components/Header/Header';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: SiteLocale }
}>) {
  // const { t } = await initTranslations(locale, ['common']);

  return (
    <html lang={locale} dir={dir(locale)}>
      <body
        className={`${ geistSans.variable } ${ geistMono.variable } antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
